openapi: 3.0.3
name: SFR用户表单
desc:
forms:
  groups:
    - title: Basic Info
      fields:
        name:
          label: Position
          required: true
          pattern: "^[_A-Za-z]+$"

        position:
          label: Position
          type: integer

    - title: Details
      fields:
        alternativeMaterial:
          label: Alternative Material
          type: integer
          format: int64
        typeOfReference:
          label: Type of Reference
          type: string
          enum:
            - Gliding
            - Option 2
            - Option 3
        thickness:
          label: Thickness in mm
          type: number
          format: double
          precision: 16
          maximum: 999999

        custom:
          label: Custom Field
          type: string
          validator:
            - trigger: 'onBlur',
            - script: !javascript |
                      (values) => { return new Promise((resolve, reject) => {
                        // 可调用全局函数
                        fetch('http://validate_api', values)
                        .then(resp => {
                          resolve(resp.code)
                        })
                        .catch(err => {
                          reject(resp.msg));
                        }
                      })}